sheep-obj := util.o vector.o map.o code.o unit.o
sheep-obj += object.o bool.o string.o name.o number.o list.o function.o alien.o
sheep-obj += unpack.o vm.o module.o read.o compile.o eval.o core.o
sheep-obj += main.o
