libsheep-obj := util.o vector.o map.o code.o gc.o
libsheep-obj += object.o bool.o string.o name.o number.o list.o \
	sequence.o foreign.o function.o alien.o
libsheep-obj += unpack.o vm.o module.o read.o parse.o compile.o eval.o core.o

sheep-obj := sheep.o
