sheep-obj := util.o vector.o map.o code.o gc.o
sheep-obj += object.o bool.o string.o name.o number.o list.o \
	sequence.o function.o alien.o
sheep-obj += unpack.o vm.o module.o read.o parse.o compile.o eval.o core.o
sheep-obj += main.o
